# Dockerfile.jinja2 for multi-stage build
FROM python:3.11-slim AS build_{{uid}}
WORKDIR /app
COPY . .

RUN python -m venv .venv
#Install uv using custom index from secret
RUN --mount=type=secret,id=pip_index_url \
    .venv/bin/pip install uv -i "$(cat /run/secrets/pip_index_url)"


# Install agent requirements using custom index from secret
RUN --mount=type=secret,id=pip_index_url \
    .venv/bin/uv pip install --index-url "$(cat /run/secrets/pip_index_url)" -r {{pyproject_file}}

RUN --mount=type=secret,id=pip_index_url \
    .venv/bin/uv lock --index-url "$(cat /run/secrets/pip_index_url)"